# Generated by Django 4.1.1 on 2022-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="student_id",
        ),
        migrations.AlterField(
            model_name="students",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
